import { format, startOfWeek } from 'date-fns';
import { DashboardData } from './types';

export function getDefaultData(): DashboardData {
  const weekOf = format(startOfWeek(new Date(), { weekStartsOn: 1 }), 'yyyy-MM-dd');
  const year = new Date().getFullYear();
  const month = new Date().getMonth();
  const quarter = `${year}-Q${Math.ceil((month + 1) / 3)}`;

  return {
    weekly: {
      weekOf,
      tasks: [],
      habits: [
        { id: '1', name: 'Exercise', icon: '💪', color: '#10b981', section: 'daily', weeklyGoal: 5, completions: {} },
        { id: '2', name: 'Read', icon: '📚', color: '#6366f1', section: 'daily', weeklyGoal: 7, completions: {} },
        { id: '3', name: 'Drink Water', icon: '💧', color: '#3b82f6', section: 'daily', weeklyGoal: 7, completions: {} },
      ],
      focus: '',
      goals: [],
    },
    quarterly: {
      [quarter]: {
        quarter,
        goals: { finance: [], health: [], school: [], personal: [] },
        finances: { creditCards: [], savings: [] },
        achievements: [],
        parkingLot: [],
      },
    },
    books: [],
    bucketList: [],
    school: {
      semesters: [],
      remainingCourses: [],
      targetDegree: 'B.S. Cybersecurity (GRC Focus)',
      totalCreditsRequired: 120,
      completedCredits: 0,
      colleges: [
        {
          id: 'wgu',
          name: 'Western Governors University',
          location: 'Online',
          type: 'nonprofit',
          programName: 'B.S. Cybersecurity and Information Assurance',
          tuitionPerYear: 3755,
          format: 'Online',
          accreditation: 'SACSCOC, ABET',
          pros: ['Flat-rate tuition', 'Self-paced', 'CAEP accredited', 'NSA/DHS CAE designated', 'Industry certifications included (Security+, CySA+, PenTest+)'],
          cons: ['No traditional campus experience', 'Requires strong self-discipline', 'Some employers prefer brick-and-mortar'],
          notes: 'Best value for working adults. GRC track well-developed.',
          applied: false,
          deadline: '2026-08-01',
          website: 'https://www.wgu.edu/online-it-degrees/cybersecurity-information-assurance-bachelors-program.html',
          score: 9,
        },
        {
          id: 'umgc',
          name: 'University of Maryland Global Campus',
          location: 'Adelphi, MD (Online)',
          type: 'public',
          programName: 'B.S. Cybersecurity Technology',
          tuitionPerYear: 12336,
          format: 'Online',
          accreditation: 'MSA/CHE, NSA CAE-CDE',
          pros: ['State university credibility', 'NSA/DHS CAE designated', 'Strong GRC and compliance focus', 'Military-friendly'],
          cons: ['Higher cost than WGU', 'Less flexible pacing'],
          notes: 'Strong government/federal career pathways. Good if targeting DoD/federal agencies.',
          applied: false,
          deadline: '2026-06-01',
          website: 'https://www.umgc.edu/online-degrees/undergraduate/cybersecurity-technology',
          score: 8,
        },
        {
          id: 'snhu',
          name: 'Southern New Hampshire University',
          location: 'Manchester, NH (Online)',
          type: 'nonprofit',
          programName: 'B.S. Cybersecurity',
          tuitionPerYear: 9600,
          format: 'Online',
          accreditation: 'NECHE',
          pros: ['Affordable', 'Flexible start dates', 'Strong student support', 'Rolling admissions'],
          cons: ['Not NSA/DHS CAE designated for all programs', 'Less research focus'],
          notes: 'Good option for broad cybersecurity education with GRC electives.',
          applied: false,
          deadline: '2026-08-01',
          website: 'https://www.snhu.edu/online-degrees/bachelors/bs-in-cybersecurity',
          score: 7,
        },
        {
          id: 'purdue',
          name: 'Purdue Global',
          location: 'Online',
          type: 'public',
          programName: 'B.S. Cybersecurity',
          tuitionPerYear: 13700,
          format: 'Online',
          accreditation: 'HLC, NSA CAE',
          pros: ['Purdue brand recognition', 'NSA/DHS CAE designated', 'Transfer-friendly', 'Strong industry connections'],
          cons: ['More expensive', 'Less GRC-specific curriculum'],
          notes: 'Strong technical reputation. Good for career advancement.',
          applied: false,
          deadline: '2026-07-01',
          website: 'https://www.purdueglobal.edu/degree-programs/information-technology/bachelor-science-cybersecurity/',
          score: 7,
        },
        {
          id: 'uiw',
          name: 'University of the Incarnate Word',
          location: 'San Antonio, TX (Hybrid)',
          type: 'private',
          programName: 'B.S. Cybersecurity',
          tuitionPerYear: 19000,
          format: 'Hybrid',
          accreditation: 'SACSCOC',
          pros: ['Hybrid option with campus access', 'Growing cybersecurity program', 'ISACA chapter access'],
          cons: ['Higher tuition', 'Less established program vs. WGU/UMGC', 'Campus required some days'],
          notes: 'Good if you prefer some in-person experience in Texas.',
          applied: false,
          deadline: '2026-06-15',
          score: 6,
        },
      ],
    },
  };
}
